name: Documentation

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    name: ${{ matrix.pkg.name }} Docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - name: GeneralisedFilters
            dir: './GeneralisedFilters'
            additional_paths: "./SSMProblems"
          - name: SSMProblems
            dir: './SSMProblems'
            additional_paths: ""
    
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1'
      - uses: julia-actions/cache@v3
        with:
          delete-old-caches: false
      - name: Install dependencies
        run: |
          julia --project=${{ matrix.pkg.dir }}/docs/ --color=yes -e '
          using Pkg;
          Pkg.Registry.update();
          paths = ["${{ matrix.pkg.dir }}"];
          extra = "${{ matrix.pkg.additional_paths }}";
          isempty(extra) || push!(paths, extra);
          Pkg.develop([PackageSpec(; path) for path in paths]);
          Pkg.instantiate();'
      - name: Build docs
        run: julia --project=${{ matrix.pkg.dir }}/docs/ ${{ matrix.pkg.dir }}/docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Insert navbar
        uses: TuringLang/actions/DocsNav@main
        with:
          doc-path: ${{ matrix.pkg.dir }}/docs/build
      - name: Deploy docs
        working-directory: ${{ matrix.pkg.dir }}/docs
        shell: julia --color=yes --project=. {0}
        run: |
          using Documenter
          deploydocs(; root=pwd(), repo="github.com/${{ github.repository }}.git",
              dirname="${{ matrix.pkg.name }}", tag_prefix="${{ matrix.pkg.name }}-",
              push_preview=true)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
